<#
.SYNOPSIS
    Renames all stimulus video files to random hex filenames and generates
    a JavaScript mapping file so the experiment code can recover the original
    metadata (letter, trial type, index) at runtime without exposing it in URLs.

.DESCRIPTION
    - Copies every .mp4 from assets/stimuli/{actual,practice}-stimuli/{letter}/
      into a flat folder assets/stimuli/v/ with randomised hex names.
    - Generates javascript/stimulus-map.js containing a lookup from hex ID
      to base64-encoded metadata ("trialType,letter,index").
    - Original files are preserved (not deleted).

.NOTES
    Run this script ONCE before deploying. Re-run it if you add or change stimuli.
    After running, upload ONLY the assets/stimuli/v/ folder to Azure Blob Storage.

.EXAMPLE
    .\scripts\obfuscate-stimuli.ps1
#>

param(
    [string]$ProjectRoot = (Split-Path $PSScriptRoot -Parent),
    [string]$StimuliRoot = $null,
    [string]$OutputDir   = $null,
    [string]$MapFile     = $null
)

# Resolve defaults relative to project root
if (-not $StimuliRoot) { $StimuliRoot = Join-Path $ProjectRoot "assets\stimuli" }
if (-not $OutputDir)   { $OutputDir   = Join-Path $StimuliRoot "v" }
if (-not $MapFile)     { $MapFile     = Join-Path $ProjectRoot "javascript\stimulus-map.js" }

Write-Host "=== Stimulus Obfuscation ==="
Write-Host "  Stimuli root : $StimuliRoot"
Write-Host "  Output folder: $OutputDir"
Write-Host "  Map file     : $MapFile"
Write-Host ""

# Create output directory (wipe if exists to avoid stale files)
if (Test-Path $OutputDir) {
    Remove-Item -Recurse -Force $OutputDir
    Write-Host "Cleared existing output folder."
}
New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null

# Collect all mp4 files (excluding the v/ output dir itself)
$files = Get-ChildItem -Path $StimuliRoot -Filter "*.mp4" -Recurse |
    Where-Object { $_.DirectoryName -notlike "*\v" -and $_.DirectoryName -notlike "*\v\*" }

if ($files.Count -eq 0) {
    Write-Error "No .mp4 files found under $StimuliRoot"
    exit 1
}

Write-Host "Found $($files.Count) video files to obfuscate.`n"

# RNG for hex IDs
$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
$usedIds = @{}
$mapEntries = @()

foreach ($file in $files) {
    # Parse folder structure: stimuli/{type}-stimuli/{letter}/{letter}_{index}.mp4
    $relativePath = $file.FullName.Substring((Resolve-Path $StimuliRoot).Path.Length + 1)
    $parts = $relativePath -split '[/\\]'

    if ($parts.Count -lt 3) {
        Write-Warning "Skipping unexpected path structure: $relativePath"
        continue
    }

    $stimFolder = $parts[0]   # "actual-stimuli" or "practice-stimuli"
    $letter     = $parts[1]   # "r", "s", "f", "j", etc.
    $filename   = $parts[2]   # "r_0.mp4"

    # Determine trial type
    if ($stimFolder -match "practice") { $trialType = "practice" }
    else { $trialType = "actual" }

    # Extract index from filename (e.g., "r_100" -> "100")
    $baseName = [System.IO.Path]::GetFileNameWithoutExtension($filename)
    $index = ($baseName -split '_' | Select-Object -Last 1)

    # Generate unique random 16-char hex ID
    do {
        $bytes = New-Object byte[] 8
        $rng.GetBytes($bytes)
        $hexId = ($bytes | ForEach-Object { $_.ToString("x2") }) -join ''
    } while ($usedIds.ContainsKey($hexId))
    $usedIds[$hexId] = $true

    # Copy file to output dir with obfuscated name
    Copy-Item $file.FullName (Join-Path $OutputDir "$hexId.mp4")

    # Base64-encode metadata: "trialType,letter,index"
    $meta = "$trialType,$letter,$index"
    $encoded = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($meta))

    $mapEntries += [PSCustomObject]@{
        HexId   = $hexId
        Encoded = $encoded
        Meta    = $meta   # for the summary output only
    }

    Write-Host "  $relativePath -> $hexId.mp4"
}

# Sort entries for deterministic output
$mapEntries = $mapEntries | Sort-Object HexId

# Generate JavaScript mapping file
$jsHeader = @'
// Auto-generated by scripts/obfuscate-stimuli.ps1 -- DO NOT EDIT MANUALLY
// Maps obfuscated video hex IDs to base64-encoded trial metadata.
// Metadata format (decoded): "trialType,letter,index"
// Re-run the script to regenerate after adding/changing stimuli.
//
// IMPORTANT: This file must be loaded AFTER config.js and BEFORE
// the experimental-pages scripts that build stimulus arrays.

const STIMULUS_MAP = {
'@

$jsFooter = @'
};

// Decode a stimulus hex ID into its original metadata.
// Returns { trialType, letter, index } or null if not found.
function _decodeStimulusMeta(hash) {
  const encoded = STIMULUS_MAP[hash];
  if (!encoded) return null;
  const parts = atob(encoded).split(',');
  return { trialType: parts[0], letter: parts[1], index: parseInt(parts[2]) };
}
'@

$mapLines = @()
foreach ($entry in $mapEntries) {
    $mapLines += '  "' + $entry.HexId + '": "' + $entry.Encoded + '",'
}

$jsContent = $jsHeader + "`n" + ($mapLines -join "`n") + "`n" + $jsFooter
Set-Content -Path $MapFile -Value $jsContent -Encoding UTF8

Write-Host ""
Write-Host "=== Done ==="
Write-Host "  Obfuscated $($mapEntries.Count) files -> $OutputDir"
Write-Host "  Generated mapping -> $MapFile"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Upload the 'assets/stimuli/v/' folder to your Azure Blob Storage container"
Write-Host "  2. Update CONFIG.stimuliBaseUrl in javascript/config.js"
Write-Host "  3. Test the experiment locally or on cognition.run"
